### ISSUE TITLE
Make scopes configurable (feature request)

### ISSUE THREAD

**Issue by ygrange** [BeryJu/oidc-test-client#10]
Heya,

I'd like to request the feature of configuring scopes. 

The pity part is that this is part of the work that has been done as part of the only fork this repo has, but the forker ( @mdusher ) has not pull-requested it. So I will just use the fork for my tests and build the container myself but also want to suggest adding this functionality to the main tool :)

**Comment by BeryJu** [comment]
I just noticed their fork also has a bunch of additional settings which make sense, I dont just want to copy those in here, I'd appreciate a PR @mdusher
