### ISSUE TITLE
Print raw id_token

### ISSUE THREAD

**Issue by jawabuu** [BeryJu/oidc-test-client#101]
Hey @BeryJu 
Many thanks for this awesome oidc client tester.
I have a feature request to print the raw id_token in the json returned for additional debugging.
It could be controlled by an optional env to maintain compatibility with the existing flow.

**Comment by jawabuu** [comment]
Thank you @BeryJu

**Comment by byron-sitawa-vectorsolutions** [comment]
@BeryJu Is there a release or a docker image with this?
